
#Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clubs
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
   showSql: true
   properties:
     hibernate:
       show_sql: true
   hibernate:
     ddlAuto: update
     dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port : 8085